import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
  namespaced: true,
  state() {
    return {
      // some dummy data to display the page
      books: [
        // {
        //   id: 1,
        //   bookName: "A Good Book",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 1,
        // },
        // {
        //   id: 2,
        //   bookName: "A Better Book",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 2,
        // },
        // {
        //   id: 3,
        //   bookName: "leap Conclude enforce",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 1,
        // },
        // {
        //   id: 4,
        //   bookName: "A Bad Book",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 1,
        // },
        // {
        //   id: 5,
        //   bookName: "Hit Below The Belt",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 2,
        // },
        // {
        //   id: 6,
        //   bookName: "Go For Broke",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 1,
        // },
        // {
        //   id: 7,
        //   bookName: "A Few Sandwiches Short of a Picnic",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 2,
        // },
        // {
        //   id: 8,
        //   bookName: "In the Red",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 1,
        // },
        // {
        //   id: 9,
        //   bookName: "Roll With the Punches",
        //   authorFirstName: "Jim",
        //   authorLastName: "Bob",
        //   publishedYear: "1995",
        //   description: "This is a description of a book",
        //   imageRef: "bookCover.png",
        //   library: 2,
        // },
      ],
      checkedOutBooks: [],
      returnedBook: [],
    };
  },
  mutations,
  actions,
  getters,
};
